### ISSUE TITLE
How to get the .hdf5 files?

### ISSUE THREAD

**Issue by kar98kbang** [Hrener/3D-Action-recognition#3]
Thanks for your code!
I have download the data from BaiduNetdisk
But how can I get the .hdf5 files to run Data_generated.py?
Could you please send it to me? My email is 1187976429@qq.com. Thank you very much!

**Comment by Hrener** [comment]
The dataset has been sent to your email, please note that check.

**Comment by sayano-lee** [comment]
Hi, could you please send me a copy of the required .hdf5 file? I emailed the author but got no reply, thx.
email: sayano.lee@gmail.com

**Comment by Viki-researcher** [comment]
> Thanks for your code!
> I have download the data from BaiduNetdisk
> But how can I get the .hdf5 files to run Data_generated.py?
> Could you please send it to me? My email is [1187976429@qq.com](mailto:1187976429@qq.com). Thank you very much!

hi，can you send me a .hdf5 file? thank you!my emil:964361584@qq.com

**Comment by 2111905222** [comment]
First of all, thank you very much for your code! Could you please send hdf5 file to me? My email is 951357158@qq.com. Best wishes to you

**Comment by sunfeng90** [comment]
Thanks，could you share me the hdf5 ？ My Email：sunfeng@zjnu.edu.cn,Thanks a lot

**Comment by kar98kbang** [comment]
Please help yourself to download these hdf5 files from Baidu Netdisk. 
link: https://pan.baidu.com/s/1Sr_4rEWnvFARAOudAIIpbQ
code: 5q5u

**Comment by sunfeng90** [comment]
> Please help yourself to download these hdf5 files from Baidu Netdisk.
> link: https://pan.baidu.com/s/1Sr_4rEWnvFARAOudAIIpbQ
> code: 5q5u

This is all the corss-view datasets?Or it's the corss-view of S0-S17?

@kar98kbang

**Comment by sunfeng90** [comment]
This project  realize all the paper’s theory?




On 07/31/2020 11:18，imaginist<notifications@github.com> wrote：

Please help yourself to download these hdf5 files from Baidu Netdisk.
link: https://pan.baidu.com/s/1Sr_4rEWnvFARAOudAIIpbQ
code: 5q5u
